
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoviron-app
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
      - MPESA_CONSUMER_SECRET=${MPESA_CONSUMER_SECRET}
      - MPESA_PASSKEY=${MPESA_PASSKEY}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - ecoviron-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      start_period: 40s
      timeout: 5s
      retries: 3

  mysql-db:
    image: mysql:8.0
    container_name: ecoviron-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ecoviron_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ecoviron-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  ecoviron-net:
