/*
FROM nginx:alpine

# # Remove default content
# RUN rm -rf /usr/share/nginx/html/*

# # Copy all frontend files including components
# COPY . /usr/share/nginx/html/

# # Set permissions
# RUN chown -R nginx:nginx /usr/share/nginx/html && \
#     chmod -R 755 /usr/share/nginx/html

# # Copy config
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]